name: Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements_test.txt
        
      - name: "Run pytest"
        uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: false
